server:
  port: 20010
  servlet:
    context-path: /zzz-system
spring:
  application:
    name: zzz-system
    namespace: platform
#  profiles:
#    active: local
  config:
    import:
      - optional:nacos:application-base.yml?group=common
      - optional:nacos:application-db.yml?group=common
      - optional:nacos:${spring.application.name}.yml?group=${spring.application.namespace}
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:18848
        group: ${spring.application.namespace}
        namespace: local
        username: nacos
        password: nacos
      config:
        server-addr: 127.0.0.1:18848
        namespace: local
        username: nacos
        password: nacos
