spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            # 注意这个设置只对 spring boot 2.4+ 有效，低版本 使用  allowedOrigins: "*" 属性
            allowedOriginPatterns: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
            exposedHeaders: "Content-Disposition,Content-Type,Cache-Control"
      routes:
        - id: zzz-auth
          uri: lb://zzz-auth
          predicates:
            - Path=/zzz-auth/**
zzz:
  gateway:
    ignore-urls:
      - /zzz-auth/token
