spring:
  datasource:
    dynamic:
      # 设置默认的数据源或者数据源组,默认值即为 master
      primary: master
      datasource:
        # 主库数据源
        master:
          driver-class-name: ${zzz-datasource.system_master.driver-class-name}
          url: ${zzz-datasource.system_master.url}
          username: ${zzz-datasource.system_master.username}
          password: ${zzz-datasource.system_master.password}
        # 从库数据源
        # slave:
        #  driver-class-name:
        #  url:
        #  username:
        #  password:
zzz:
  mybatis-plus:
    multi-tenant:
      ignore-tables:
        - sys_user
        - sys_client
  log:
    path: /Users/zhouzq/logs/zzz
