spring:
  cloud:
    gateway:
      routes:
        - id: zzz-oauth
          uri: lb://zzz-oauth
          predicates:
            - Path=/zzz-oauth/**
        - id: zzz-system
          uri: lb://zzz-system
          predicates:
            - Path=/zzz-system/**
