server:
  port: 20000
spring:
  application:
    name: zzz-gateway
    namespace: platform
  #  profiles:
  #    active: local
  config:
    import:
      - optional:nacos:application-base.yml?group=common
      - optional:nacos:application-cache.yml?group=common
      - optional:nacos:${spring.application.name}.yml?group=${spring.application.namespace}
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:18848
        group: ${spring.application.namespace}
        namespace: local
        username: nacos
        password: nacos
      config:
        server-addr: 127.0.0.1:18848
        namespace: local
        username: nacos
        password: nacos
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
zzz:
  log:
    path: D:\logs\zzz-cloud\${spring.application.name}
